config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'patients#index'

  resources :patients do 
    collection {post :import}
  end
  resources :posts
  resources :comments, only: [:create, :new]
  resources :users, only: [:show, :create, :edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get '/dashboards', to: 'dashboards#index'
  post '/dashboards', to: 'dashboards#show'

end

app/models/Comment.rb
class Comment< ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true 

end 

app/models/Gap.rb
class Gap < ActiveRecord::Base

  belongs_to :patient
  belongs_to :measure
  belongs_to :task

  has_many :payer_codes

end 

app/models/Measure.rb
class Measure < ActiveRecord::Base

  has_many :patient_measures
  has_many :patients, through: :patient_measures
  
  belongs_to :plan 

  has_many :payer_codes

  has_many :tasks 

  has_one :gap 

end 

app/models/Patient.rb
class Patient < ActiveRecord::Base 

has_many :gaps


has_many :user_patients
has_many :users, through: :user_patients

has_many :patient_plans
has_many :plans, through: :patient_plans

has_many :provider_patients
has_many :providers, through: :provider_patients

has_many :patient_measures
has_many :measures, through: :patient_measures

has_many :patient_tasks
has_many :tasks, through: :patient_tasks

has_many :patient_posts
has_many :posts, through: :patient_posts


def full_name
  [self.firstname, self.middlename, self.lastname].reject {|s| s.nil?}.join(' ') 
end 

def self.import(file, plan)
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i| 
    row = Hash[[header, spreadsheet.row(i)].transpose]
    patient = find_by_id(row["id"]) || new 
    patient.attributes = row.to_hash.slice("firstname", "lastname", "cellphone")
    patient.save!
    patient.plans << plan  
 
  end 
end 

def self.open_spreadsheet(file)

  case File.extname(file.original_filename)
  when ".csv" then Roo::Csv.new(file.path, nil, :ignore) 
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore) 
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore) 
  else raise "Unknown file type: #{file.original_filename} "
  end 

end 



end 

app/models/Patient_Measure.rb
class PatientMeasure < ActiveRecord::Base

belongs_to :patient
belongs_to :measure
  
end 

app/models/Patient_Plan.rb
class PatientPlan < ActiveRecord::Base

belongs_to :patient
belongs_to :plan
  
end 

app/models/Patient_Post.rb
class PatientPost< ActiveRecord::Base

belongs_to :patient
belongs_to :post
  
end 

app/models/Patient_Task.rb
class PatientTask< ActiveRecord::Base

belongs_to :patient
belongs_to :task
  
end 

app/models/Payer_Code.rb
class PayerCode < ActiveRecord::Base

  belongs_to :measure
  belongs_to :plan 

  belongs_to :gap

end 

app/models/Plan.rb
class Plan< ActiveRecord::Base

  has_many :patient_plans
  has_many :patients, through: :patient_plans

  has_many :measures

  has_many :payer_codes

  has_many :tasks

end 

app/models/Post.rb
class Post < ActiveRecord::Base
  
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments

  has_many :patient_posts
  has_many :patients, through: :patient_posts

  validates :description, presence: true 
end 

app/models/Practice.rb
class Practice < ActiveRecord::Base
  has_many :providers

end 

app/models/Provider.rb
class Provider < ActiveRecord::Base
 has_many :user_providers
 has_many :users, through: :user_providers

 belongs_to :practice

has_many :provider_patients
has_many :patients, through: :provider_patients

end 

app/models/Provider_Patient.rb
class ProviderPatient < ActiveRecord::Base

belongs_to :provider
belongs_to :patient
  
end 

app/models/Task.rb
class Task < ActiveRecord::Base
  
  belongs_to :plan
  belongs_to :measure 

  has_many :patient_tasks
  has_many :patients, through: :patient_tasks

  has_many :gaps 


end 

app/models/User.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  has_many :user_providers
  has_many :providers, through: :user_providers

  has_many :user_patients
  has_many :patients, through: :user_patients

  has_secure_password validations: false 
  #validates :user_name, presence: true, uniqueness: true 
  #validates :password, presence: true, on: :create, length: {minimum: 8}

  def full_name
  [self.first_name, self.last_name].reject {|s| s.nil?}.join(' ') 
  end 

end 

app/models/User_Patient.rb
class UserPatient < ActiveRecord::Base

belongs_to :user
belongs_to :patient
  
end 

app/models/User_Provider.rb
class UserProvider < ActiveRecord::Base

belongs_to :user
belongs_to :provider
  
end 

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def index
    @patients = Patient.all
  end

  def show
     @patient = Patient.find(params[:id])
     @post = Post.new
     @comment = Comment.new 
  end 

  def new
    @plans = Plan.all 
    @patient = Patient.new 
  end

  def create

  end

  def edit

  end 

  def import

    binding.pry

    Patient.import(params[:file], Plan.find(params[:plan]))
    flash[:notice] = "Patients imported"
    redirect_to root_path 

  end  

end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def new
  end 

  def create
    @post = Post.new(post_params)
    @post.creator = current_user
   
    if @post.save
     
      @post.patients << Patient.find(params[:patient_id])
      flash[:notice] = "Patient account noted"
      redirect_to :back 

    else 
      flash[:error] = "Notes cannot be entered blank"
      redirect_to :back
    end 
  end 

end

  private

  def post_params
    params.require(:post).permit(:description)
    
  end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/patients/edit.html.erb
<%= render 'shared/content_title', title: "Edit Patient Information" %> 

app/views/patients/index.html.erb
<h3> MaximizeMD!<h3> 
<h5><ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">All Tasks</a></li>
  <li role="presentation"><a href="tasks{:id} or measure{id} or plan{:id}">Highmark Tasks</a></li>
  <li role="presentation"><a href="#">UPMC Tasks</a></li>
   <li role="presentation"><a href="#">Aetna Tasks</a></li>
</ul><h5>

<% @patients.each do |patient| %> 
    <div class='span8 well'>

      <h4>
      <%= link_to patient.full_name, patient_path(patient)%> has gaps in care
      </br> 
      <%= patient.tasks.size %> tasks to be completed for <%=patient.plans.first.insurance %>, <%= patient.plans.first.plan_title %> 


    </div>

    <% end %> 

app/views/patients/new.html.erb
<%= render 'shared/content_title', title: "Mass import from file or add single patient" %> 

<%= form_tag import_patients_path, multipart: true do %> 
<%= file_field_tag :file %> 
<%= submit_tag "Import", class: 'btn btn-info btn-small'  %> 
<% end %> 

<hr>

app/views/patients/show.html.erb
<%= render 'shared/content_title', title: "Patient Account" %> 

<p class = 'pull-right'>
[<%= link_to("edit patient", edit_patient_path(@patient))%>]
</p>

<h4> <%= @patient.full_name %> <h4> 

  I need to list out all of the tasks on a patient
  put all of his contact information to the screen
  allow for a post on his account and show all posts for this patient. 
    track the user who posted it 
    timestamp it
    errors
    strong parameters 

  </br>

  <hr> 
    <ul> 
    <% @patient.tasks.each do |task| %> 
    <li><%= task.description %></li>  
    <%end%> 
  </ul>
 <hr>


  <div class='well'> 
    <%= form_for @post do |f| %> 
      <div class = 'control-group'> 
        <%= f.label :Notes %> 
        <%= f.text_area :description, :cols => "80", :rows => "5" %>
      </div> 

      <%= f.submit 'Enter Notes', class: 'btn btn-primary' %>
       <%= hidden_field_tag :patient_id, @patient.id %> 

    <% end %> 

  </div> 


  <% @patient.posts.each do |post| %> 
  <div class='well'>  
      <%= post.description %>
        <span class = 'quiet'>Posted by </span> <%= link_to post.creator.first_name + ' ' + post.creator.last_name, ' ' %> 
        <small>at <%= post.created_at %></small>
      

        <% post.comments.each do |comment| %>

        <li><%= comment.body %> 
        <span class = 'quiet'>reply from </span> <%= link_to comment.creator.first_name + ' ' + comment.creator.last_name, ' ' %> 
        <small>at <%= comment.created_at %></small></li>
        <% end %> 
      </br></br>

      

        <%= form_for @comment do |c| %> 
           
          <%= c.text_field :body %> 
          <%= c.submit 'Reply', class: 'btn' %>
          <%= hidden_field_tag :post_id, post.id %>  
        <% end %> 

  </div>
  
  <% end %> 