config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'patients#index'

  resources :patients do 
    collection {post :import}
  end
  resources :posts
  resources :comments, only: [:create, :new]
  resources :users, only: [:show, :create, :edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get '/dashboards', to: 'dashboards#index'
  post '/dashboards', to: 'dashboards#show'

end

app/models/Comment.rb
class Comment< ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true 

end 

app/models/Gap.rb
class Gap < ActiveRecord::Base

  belongs_to :patient
  belongs_to :measure
  belongs_to :task

  has_many :payer_codes

end 

app/models/Measure.rb
class Measure < ActiveRecord::Base

  has_many :patient_measures
  has_many :patients, through: :patient_measures
  
  belongs_to :plan 

  has_many :payer_codes

  has_many :tasks 

  has_one :gap 

end 

app/models/Patient.rb
class Patient < ActiveRecord::Base 

has_many :gaps


has_many :user_patients
has_many :users, through: :user_patients

has_many :patient_plans
has_many :plans, through: :patient_plans

has_many :provider_patients
has_many :providers, through: :provider_patients

has_many :patient_measures
has_many :measures, through: :patient_measures

has_many :patient_tasks
has_many :tasks, through: :patient_tasks

has_many :patient_posts
has_many :posts, through: :patient_posts


def full_name
  [self.firstname, self.middlename, self.lastname].reject {|s| s.nil?}.join(' ') 
end 

def self.import(file, plan)
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i| 
    row = Hash[[header, spreadsheet.row(i)].transpose]
    patient = find_by_id(row["id"]) || new 
    patient.attributes = row.to_hash.slice("firstname", "lastname", "cellphone")
    patient.save!
    patient.plans << plan  
 
  end 
end 

def self.open_spreadsheet(file)

  case File.extname(file.original_filename)
  when ".csv" then Roo::Csv.new(file.path, nil, :ignore) 
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore) 
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore) 
  else raise "Unknown file type: #{file.original_filename} "
  end 

end 



end 

app/models/Patient_Measure.rb
class PatientMeasure < ActiveRecord::Base

belongs_to :patient
belongs_to :measure
  
end 

app/models/Patient_Plan.rb
class PatientPlan < ActiveRecord::Base

belongs_to :patient
belongs_to :plan
  
end 

app/models/Patient_Post.rb
class PatientPost< ActiveRecord::Base

belongs_to :patient
belongs_to :post
  
end 

app/models/Patient_Task.rb
class PatientTask< ActiveRecord::Base

belongs_to :patient
belongs_to :task
  
end 

app/models/Payer_Code.rb
class PayerCode < ActiveRecord::Base

  belongs_to :measure
  belongs_to :plan 

  belongs_to :gap

end 

app/models/Plan.rb
class Plan< ActiveRecord::Base

  has_many :patient_plans
  has_many :patients, through: :patient_plans

  has_many :measures

  has_many :payer_codes

  has_many :tasks

end 

app/models/Post.rb
class Post < ActiveRecord::Base
  
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments

  has_many :patient_posts
  has_many :patients, through: :patient_posts

  validates :description, presence: true 
end 

app/models/Practice.rb
class Practice < ActiveRecord::Base
  has_many :providers

end 

app/models/Provider.rb
class Provider < ActiveRecord::Base
 has_many :user_providers
 has_many :users, through: :user_providers

 belongs_to :practice

has_many :provider_patients
has_many :patients, through: :provider_patients

end 

app/models/Provider_Patient.rb
class ProviderPatient < ActiveRecord::Base

belongs_to :provider
belongs_to :patient
  
end 

app/models/Task.rb
class Task < ActiveRecord::Base
  
  belongs_to :plan
  belongs_to :measure 

  has_many :patient_tasks
  has_many :patients, through: :patient_tasks

  has_many :gaps 


end 

app/models/User.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  has_many :user_providers
  has_many :providers, through: :user_providers

  has_many :user_patients
  has_many :patients, through: :user_patients

  has_secure_password validations: false 
  #validates :user_name, presence: true, uniqueness: true 
  #validates :password, presence: true, on: :create, length: {minimum: 8}

  def full_name
  [self.first_name, self.last_name].reject {|s| s.nil?}.join(' ') 
  end 

end 

app/models/User_Patient.rb
class UserPatient < ActiveRecord::Base

belongs_to :user
belongs_to :patient
  
end 

app/models/User_Provider.rb
class UserProvider < ActiveRecord::Base

belongs_to :user
belongs_to :provider
  
end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def new
  end 

  def create
    @post = Post.new(post_params)
    @post.creator = current_user
   
    if @post.save
     
      @post.patients << Patient.find(params[:patient_id])
      flash[:notice] = "Patient account noted"
      redirect_to :back 

    else 
      flash[:error] = "Notes cannot be entered blank"
      redirect_to :back
    end 
  end 

end

  private

  def post_params
    params.require(:post).permit(:description)
    
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Maximize MD", root_path, :class => 'brand' %>
  </li>
</ul>

<div class='nav_item'>
  <%= link_to 'Dashboards', dashboards_path, class: 'btn btn-warning btn-small' %> 
</div> 

<div class='nav_item'>
  <%= link_to 'Add Patients', new_patient_path, class: 'btn btn-success btn-small' %> 
</div> 

<div class='btn-group nav_item'>
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Reports 
     <span class='caret'></span> 
  <%end%> 

    <ul class='dropdown-menu'>

        <li>
          <%= link_to edit_user_path(current_user) do %>
          <i class ='icon-pencil'></i> 
          Financial Reports
          <% end %>   

        </li> 
        

        <li>
          <%= link_to user_path(current_user) do %>
          <i class ='icon-user'></i> 
          Status Reports
          <% end %>   

        </li> 
     
        <li class='divider'></li> 
        <li>
          <%= link_to(logout_path) do %> 
            <i class="icon-circle-arrow-left"></i>
           Create Reports
            <% end %> 
        </li> 
      </ul> 
  </div> 


<% if logged_in? %> 

<div class='btn-group nav_item'>
  
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    <%= current_user.full_name %>  
     <span class='caret'></span> 
  <%end%> 

    <ul class='dropdown-menu'>

        <li>
          <%= link_to edit_user_path(current_user) do %>
          <i class ='icon-pencil'></i> 
          edit profile
          <% end %>   

        </li> 
        

        <li>
          <%= link_to user_path(current_user) do %>
          <i class ='icon-user'></i> 
          view profile
          <% end %>   

        </li> 
     
        <li class='divider'></li> 
        <li>
          <%= link_to(logout_path) do %> 
            <i class="icon-circle-arrow-left"></i>
            logout
            <% end %> 
        </li> 
      </ul> 
   
  </div> 

  <% end %> 

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/shared/_check_login.html.erb
<% if !logged_in? %> 
<%= render 'login' %>
<%end%>  

app/views/shared/_content_title.html.erb
<p class='lead'> 
  <h3><%= title %></h3> 
  <hr/> 
</p>

app/views/shared/_errors.html.erb
<% binding.pry %> 
<% if obj.errors.any? %> 
  <div class='row'>
    <div class = 'alert alert-error span8'>
      <h5> Please fix the following <h5> 
        
        <% obj.errors.full_messages.each do |msg| %> 
        <li> <%= msg %> </li> 
        <%end%> 
    </div>
  </div> 
<%end%> 